[package]
name = "path_tracer"
version = "0.1.0"
description = "Path tracer"
license = "MIT"
authors = ["Matt Godbolt <matt@godbolt.org>"]

[[bin]]
name = "path_tracer"
path = "src/main.rs"

[dependencies]
rand = "0.3"
threadpool = "0.1"
num_cpus = "0.2"
argparse = "*"
